export const categories = [
  {
    id: '1',
    name: 'Pizza',
    image: require('../assets/images/categories/icons8-pizza-96.png'),
  },
  {
    id: '2',
    name: 'Burgers',
    image: require('../assets/images/categories/icons8-pizza-96.png'),
  },
  {
    id: '3',
    name: 'Sushi',
    image: require('../assets/images/categories/icons8-pizza-96.png'),
  },
  {
    id: '4',
    name: 'Desserts',
    image: require('../assets/images/categories/icons8-pizza-96.png'),
  },
  {
    id: '5',
    name: 'Drinks',
    image: require('../assets/images/categories/icons8-pizza-96.png'),
  },
  {
    id: '6',
    name: 'Salads',
    image: require('../assets/images/categories/icons8-pizza-96.png'),
  },
];

export const featuredOld = {
  id: 1,
  title: "Hot n Spicy",
  desc: "soft & tender fried chicken",
  restaurants: [
    {
      id: 'res001',
      name: 'Sushi Zen',
      image: require('../assets/images/restaurants/res-5.jpg'),
      description: 'Traditional Japanese sushi with a modern twist.',
      lat: 19.076,
      lng: 72.8777,
      address: '123 Tokyo Lane, Mumbai',
      stars: 4.8,
      reviews: '1.2k',
      category: 'Japanese',
      dishes: [
        {
          id: 'dish001',
          name: 'Salmon Nigiri',
          description: 'Fresh salmon over seasoned rice.',
          price: 299,
          image: require('../assets/images/dishes/dish-1.jpeg'),
        },
        {
          id: 'dish002',
          name: 'Tuna Roll',
          description: 'Tuna, avocado and cucumber wrapped in seaweed.',
          price: 349,
          image: require('../assets/images/dishes/dish-2.jpeg'),
        },
      ],
    },
    {
      id: 'res002',
      name: 'Burger Hub',
      image: require('../assets/images/restaurants/res-5.jpg'),
      description: 'Juicy burgers with handcrafted buns and sauces.',
      lat: 19.2183,
      lng: 72.9781,
      address: '56 Grill Street, Mumbai',
      stars: 4.5,
      reviews: '2.3k',
      category: 'American',
      dishes: [
        {
          id: 'dish003',
          name: 'Cheeseburger',
          description: 'Grilled beef patty with cheddar and pickles.',
          price: 199,
          image: require('../assets/images/dishes/dish-3.jpeg'),
        },
        {
          id: 'dish004',
          name: 'Veggie Deluxe',
          description: 'Crispy veg patty with lettuce and mayo.',
          price: 179,
          image: require('../assets/images/dishes/dish-4.jpeg'),
        },
      ],
    },
    {
      id: 'res003',
      name: 'Taco Fiesta',
      image: require('../assets/images/restaurants/res-5.jpg'),
      description: 'Authentic Mexican tacos, burritos and more.',
      lat: 19.033,
      lng: 73.0297,
      address: '89 Salsa Ave, Navi Mumbai',
      stars: 4.6,
      reviews: '1.9k',
      category: 'Mexican',
      dishes: [
        {
          id: 'dish005',
          name: 'Chicken Taco',
          description: 'Spicy grilled chicken with pico de gallo.',
          price: 149,
          image: require('../assets/images/dishes/dish-5.jpeg'),
        },
        {
          id: 'dish006',
          name: 'Bean Burrito',
          description: 'Soft burrito with beans and cheese.',
          price: 169,
          image: require('../assets/images/dishes/dish-6.jpeg'),
        },
      ],
    },
    {
      id: 'res004',
      name: 'Pasta Palace',
      image: require('../assets/images/restaurants/res-5.jpg'),
      description: 'Classic Italian pastas and homemade sauces.',
      lat: 19.0765,
      lng: 72.8902,
      address: '12 Roma Road, Mumbai',
      stars: 4.7,
      reviews: '2.1k',
      category: 'Italian',
      dishes: [
        {
          id: 'dish007',
          name: 'Spaghetti Bolognese',
          description: 'Rich meat sauce on al dente spaghetti.',
          price: 249,
          image: require('../assets/images/dishes/dish-7.jpeg'),
        },
        {
          id: 'dish008',
          name: 'Penne Alfredo',
          description: 'Creamy white sauce with herbs.',
          price: 229,
          image: require('../assets/images/dishes/dish-8.jpeg'),
        },
      ],
    },
    {
      id: 'res005',
      name: 'The Curry Bowl',
      image: require('../assets/images/restaurants/res-5.jpg'),
      description: 'Bold Indian flavors in every bite.',
      lat: 19.089,
      lng: 72.8654,
      address: '101 Spice Street, Andheri',
      stars: 4.9,
      reviews: '3.5k',
      category: 'Indian',
      dishes: [
        {
          id: 'dish009',
          name: 'Butter Chicken',
          description: 'Creamy tomato gravy with grilled chicken.',
          price: 299,
          image: require('../assets/images/dishes/dish-9.jpeg'),
        },
        {
          id: 'dish010',
          name: 'Paneer Tikka',
          description: 'Grilled paneer cubes marinated in spices.',
          price: 249,
          image: require('../assets/images/dishes/dish-10.jpeg'),
        },
      ],
    },
    {
      id: 'res006',
      name: 'Green Bowl',
      image: require('../assets/images/restaurants/res-5.jpg'),
      description: 'Healthy and fresh vegetarian meals.',
      lat: 19.109,
      lng: 72.8432,
      address: '77 Wellness Lane, Bandra',
      stars: 4.4,
      reviews: '1.6k',
      category: 'Healthy',
      dishes: [
        {
          id: 'dish011',
          name: 'Quinoa Salad',
          description: 'Protein-packed salad with veggies.',
          price: 199,
          image: require('../assets/images/dishes/dish-11.jpeg'),
        },
        {
          id: 'dish012',
          name: 'Avocado Toast',
          description: 'Toasted bread with smashed avocado and seeds.',
          price: 189,
          image: require('../assets/images/dishes/dish-12.jpeg'),
        },
      ],
    },
  ],
};

export const featured = {
  id: 1,
  title: "Hot n Spicy",
  desc: "Soft & tender fried chicken",
  restaurants: [
    {
      id: 'res001',
      name: 'Sushi Zen',
      image: require('../assets/images/restaurants/res-1.webp'),
      description: 'Traditional Japanese sushi with a modern twist.',
      lat: 19.076,
      lng: 72.8777,
      address: '123 Tokyo Lane, Mumbai',
      stars: 4.8,
      reviews: '1.2k',
      category: 'Japanese',
      dishes: [
        {
          id: 'dish001',
          name: 'Salmon Nigiri',
          description: 'Fresh salmon over seasoned rice.',
          price: 299,
          image: require('../assets/images/dishes/dish-1.jpeg'),
        },
        {
          id: 'dish002',
          name: 'Tuna Roll',
          description: 'Tuna, avocado and cucumber wrapped in seaweed.',
          price: 349,
          image: require('../assets/images/dishes/dish-2.jpeg'),
        },
        {
          id: 'dish003',
          name: 'Shrimp Tempura',
          description: 'Crispy fried shrimp with sauce.',
          price: 399,
          image: require('../assets/images/dishes/dish-3.jpeg'),
        },
        {
          id: 'dish004',
          name: 'Miso Soup',
          description: 'Warm soup with tofu and seaweed.',
          price: 129,
          image: require('../assets/images/dishes/dish-4.jpeg'),
        },
      ],
    },
    {
      id: 'res002',
      name: 'Burger Hub',
      image: require('../assets/images/restaurants/res-2.webp'),
      description: 'Juicy burgers with handcrafted buns and sauces.',
      lat: 19.2183,
      lng: 72.9781,
      address: '56 Grill Street, Mumbai',
      stars: 4.5,
      reviews: '2.3k',
      category: 'American',
      dishes: [
        {
          id: 'dish005',
          name: 'Cheeseburger',
          description: 'Grilled beef patty with cheddar and pickles.',
          price: 199,
          image: require('../assets/images/dishes/dish-5.jpeg'),
        },
        {
          id: 'dish006',
          name: 'Veggie Deluxe',
          description: 'Crispy veg patty with lettuce and mayo.',
          price: 179,
          image: require('../assets/images/dishes/dish-6.jpeg'),
        },
        {
          id: 'dish007',
          name: 'Double Trouble',
          description: 'Double patty with extra cheese.',
          price: 249,
          image: require('../assets/images/dishes/dish-7.jpeg'),
        },
        {
          id: 'dish008',
          name: 'Fries Bucket',
          description: 'Golden crispy fries.',
          price: 99,
          image: require('../assets/images/dishes/dish-8.jpeg'),
        },
      ],
    },
    {
      id: 'res003',
      name: 'Taco Fiesta',
      image: require('../assets/images/restaurants/res-3.jpeg'),
      description: 'Authentic Mexican tacos, burritos and more.',
      lat: 19.033,
      lng: 73.0297,
      address: '89 Salsa Ave, Navi Mumbai',
      stars: 4.6,
      reviews: '1.9k',
      category: 'Mexican',
      dishes: [
        {
          id: 'dish009',
          name: 'Chicken Taco',
          description: 'Spicy grilled chicken with pico de gallo.',
          price: 149,
          image: require('../assets/images/dishes/dish-9.jpeg'),
        },
        {
          id: 'dish010',
          name: 'Bean Burrito',
          description: 'Soft burrito with beans and cheese.',
          price: 169,
          image: require('../assets/images/dishes/dish-10.jpeg'),
        },
        {
          id: 'dish011',
          name: 'Nacho Bowl',
          description: 'Loaded nachos with cheese and jalapeños.',
          price: 199,
          image: require('../assets/images/dishes/dish-11.jpeg'),
        },
        {
          id: 'dish012',
          name: 'Mexican Rice',
          description: 'Spiced rice with corn and beans.',
          price: 139,
          image: require('../assets/images/dishes/dish-12.jpeg'),
        },
      ],
    },
    {
      id: 'res004',
      name: 'Pasta Palace',
      image: require('../assets/images/restaurants/res-4.jpg'),
      description: 'Classic Italian pastas and homemade sauces.',
      lat: 19.0765,
      lng: 72.8902,
      address: '12 Roma Road, Mumbai',
      stars: 4.7,
      reviews: '2.1k',
      category: 'Italian',
      dishes: [
        {
          id: 'dish013',
          name: 'Spaghetti Bolognese',
          description: 'Rich meat sauce on al dente spaghetti.',
          price: 249,
          image: require('../assets/images/dishes/dish-13.jpeg'),
        },
        {
          id: 'dish014',
          name: 'Penne Alfredo',
          description: 'Creamy white sauce with herbs.',
          price: 229,
          image: require('../assets/images/dishes/dish-14.jpeg'),
        },
        {
          id: 'dish015',
          name: 'Garlic Bread',
          description: 'Toasted bread with garlic butter.',
          price: 89,
          image: require('../assets/images/dishes/dish-15.jpeg'),
        },
        {
          id: 'dish016',
          name: 'Lasagna',
          description: 'Layered pasta with meat and cheese.',
          price: 279,
          image: require('../assets/images/dishes/dish-1.jpeg'),
        },
      ],
    },
    {
      id: 'res005',
      name: 'The Curry Bowl',
      image: require('../assets/images/restaurants/res-5.jpg'),
      description: 'Bold Indian flavors in every bite.',
      lat: 19.089,
      lng: 72.8654,
      address: '101 Spice Street, Andheri',
      stars: 4.9,
      reviews: '3.5k',
      category: 'Indian',
      dishes: [
        {
          id: 'dish017',
          name: 'Butter Chicken',
          description: 'Creamy tomato gravy with grilled chicken.',
          price: 299,
          image: require('../assets/images/dishes/dish-2.jpeg'),
        },
        {
          id: 'dish018',
          name: 'Paneer Tikka',
          description: 'Grilled paneer cubes marinated in spices.',
          price: 249,
          image: require('../assets/images/dishes/dish-3.jpeg'),
        },
        {
          id: 'dish019',
          name: 'Dal Makhani',
          description: 'Slow-cooked black lentils in rich gravy.',
          price: 199,
          image: require('../assets/images/dishes/dish-4.jpeg'),
        },
        {
          id: 'dish020',
          name: 'Naan Basket',
          description: 'Assortment of butter and garlic naan.',
          price: 99,
          image: require('../assets/images/dishes/dish-5.jpeg'),
        },
      ],
    },
    {
      id: 'res006',
      name: 'Green Bowl',
      image: require('../assets/images/restaurants/res-1.webp'),
      description: 'Healthy and fresh vegetarian meals.',
      lat: 19.109,
      lng: 72.8432,
      address: '77 Wellness Lane, Bandra',
      stars: 4.4,
      reviews: '1.6k',
      category: 'Healthy',
      dishes: [
        {
          id: 'dish021',
          name: 'Quinoa Salad',
          description: 'Protein-packed salad with veggies.',
          price: 199,
          image: require('../assets/images/dishes/dish-6.jpeg'),
        },
        {
          id: 'dish022',
          name: 'Avocado Toast',
          description: 'Toasted bread with smashed avocado and seeds.',
          price: 189,
          image: require('../assets/images/dishes/dish-7.jpeg'),
        },
        {
          id: 'dish023',
          name: 'Fruit Bowl',
          description: 'Mixed seasonal fruits with yogurt.',
          price: 149,
          image: require('../assets/images/dishes/dish-8.jpeg'),
        },
        {
          id: 'dish024',
          name: 'Veggie Wrap',
          description: 'Fresh vegetables wrapped in a soft tortilla.',
          price: 179,
          image: require('../assets/images/dishes/dish-9.jpeg'),
        },
      ],
    },
  ],
};

